INSERT INTO ACCOUNT
(AC_NUM, AC_NAME, AC_PHONE, AC_ADD, AC_BOWNER, AC_BNUM, AC_BNAME)
VALUES('AC_'||TO_CHAR(LPAD(TO_CHAR(AC_NUM_SEQ.NEXTVAL),3,'0'))
,'더나와','02-7845-2236','서울특별시 용산구','이재민','213-224321-07563','하나은행');


INSERT INTO CD_ORDER(CD_NUM, CD_SORT, CD_DATE, CD_PRICE, C_NUM)
VALUES(TO_CHAR(sysdate, 'yymmdd')||TO_CHAR(LPAD(TO_CHAR(CD_NUM_SEQ.NEXTVAL),4,'0')),
'취소완료',SYSDATE,2120000,'C_001');


INSERT INTO CUSTOMER
(C_NUM, C_NAME, C_ID, C_PW, C_PHONE, C_ADD, C_BIRTH, C_EMAIL)
VALUES(C_NUM_SEQ.NEXTVAL,'고객명','비밀번호','전화번호','주소','생년월일','이메일');


INSERT INTO ORDER_CHART
(CH_NUM, CD_NUM, CH_QTY, P_NUM)
VALUES(CH_NUM_SEQ.NEXTVAL,'SW_003',2,'1911060001');


INSERT INTO PRODUCT
(P_NAME, P_PRICE, P_SIZE, P_GRT, P_DATE, P_IMG, P_QTY, P_NUM)
VALUES('제품명',가격,'크기','보증기간',SYSDATE,'이미지명',개수,'제품번호');


INSERT INTO WAREHOUSE
(WH_NUM, WH_QTY, AC_NUM, P_NUM)
VALUES(WH_NUM_SEQ.NEXTVAL,개수,'AC_001','제품번호');

