
CREATE TABLE ACCOUNT
(
	AC_NUM               VARCHAR2(6) NOT NULL ,
	AC_NAME              VARCHAR2(30) NOT NULL ,
	AC_PHONE             VARCHAR2(13) NOT NULL ,
	AC_ADD               VARCHAR2(60) NOT NULL ,
	AC_BOWNER            VARCHAR2(12) NOT NULL ,
	AC_BNUM              VARCHAR2(16) NOT NULL ,
	AC_BNAME             VARCHAR2(30) NOT NULL ,
	AC_REG               DATE DEFAULT  SYSDATE  NULL 
);



CREATE UNIQUE INDEX AC_NUM_PK ON ACCOUNT
(AC_NUM   ASC);



ALTER TABLE ACCOUNT
	ADD CONSTRAINT  AC_NUM_PK PRIMARY KEY (AC_NUM);



ALTER TABLE ACCOUNT
ADD CONSTRAINT  D_BNUM_UK UNIQUE (AC_BNUM);



CREATE TABLE CD_ORDER
(
	CD_NUM               VARCHAR2(10) NOT NULL ,
	CD_SORT              VARCHAR2(12) DEFAULT  '°Å·¡Áß'  NULL ,
	CD_REG               DATE DEFAULT  SYSDATE  NULL ,
	CD_PRICE             NUMBER DEFAULT  0  NOT NULL ,
	C_NUM                VARCHAR2(5) NOT NULL 
);



CREATE UNIQUE INDEX CD_NUM_PK ON CD_ORDER
(CD_NUM   ASC);



ALTER TABLE CD_ORDER
	ADD CONSTRAINT  CD_NUM_PK PRIMARY KEY (CD_NUM);



CREATE  INDEX C_NUM_FK ON CD_ORDER
(C_NUM   ASC);



CREATE TABLE CUSTOMER
(
	C_NUM                VARCHAR2(5) NOT NULL ,
	C_NAME               VARCHAR2(12) NOT NULL ,
	C_ID                 VARCHAR2(30) NOT NULL ,
	C_PW                 VARCHAR2(30) NOT NULL ,
	C_PHONE              VARCHAR2(13) NOT NULL ,
	C_ADD                VARCHAR2(60) NOT NULL ,
	C_BIRTH              DATE NOT NULL ,
	C_EMAIL              VARCHAR2(50) NOT NULL ,
	C_REG                DATE DEFAULT  SYSDATE  NULL 
);



CREATE UNIQUE INDEX C_NUM_PK ON CUSTOMER
(C_NUM   ASC);



ALTER TABLE CUSTOMER
	ADD CONSTRAINT  C_NUM_PK PRIMARY KEY (C_NUM);



ALTER TABLE CUSTOMER
ADD CONSTRAINT  C_ID_UK UNIQUE (C_ID);



CREATE TABLE ORDER_CHART
(
	CH_NUM               VARCHAR2(6) NOT NULL ,
	CD_NUM               VARCHAR2(10) NOT NULL ,
	CH_QTY               NUMBER DEFAULT  0  NOT NULL ,
	P_NUM                VARCHAR2(6) NOT NULL 
);



CREATE UNIQUE INDEX CH_NUM_PK ON ORDER_CHART
(CH_NUM   ASC);



ALTER TABLE ORDER_CHART
	ADD CONSTRAINT  CH_NUM_PK PRIMARY KEY (CH_NUM);



CREATE  INDEX CD_NUM_FK ON ORDER_CHART
(CD_NUM   ASC);



CREATE  INDEX P_NUM_FK ON ORDER_CHART
(P_NUM   ASC);



CREATE TABLE PRODUCT
(
	P_NAME               VARCHAR2(200) NOT NULL ,
	P_PRICE              NUMBER DEFAULT  0  NOT NULL ,
	P_SIZE               VARCHAR2(120) NULL ,
	P_GRT                VARCHAR2(30) NULL ,
	P_DATE               DATE NULL ,
	P_IMG                VARCHAR2(150) NOT NULL ,
	P_QTY                NUMBER DEFAULT  0  NULL ,
	P_NUM                VARCHAR2(6) NOT NULL ,
	P_REG                DATE DEFAULT  SYSDATE  NULL 
);



CREATE UNIQUE INDEX P_NUM_PK ON PRODUCT
(P_NUM   ASC);



ALTER TABLE PRODUCT
	ADD CONSTRAINT  P_NUM_PK PRIMARY KEY (P_NUM);



CREATE TABLE WAREHOUSE
(
	WH_NUM               VARCHAR2(7) NOT NULL ,
	WH_QTY               NUMBER NOT NULL ,
	AC_NUM               VARCHAR2(6) NOT NULL ,
	P_NUM                VARCHAR2(6) NOT NULL ,
	WH_REG               DATE DEFAULT  SYSDATE  NULL 
);



CREATE UNIQUE INDEX WH_NUM_PK ON WAREHOUSE
(WH_NUM   ASC);



ALTER TABLE WAREHOUSE
	ADD CONSTRAINT  WH_NUM_PK PRIMARY KEY (WH_NUM);



CREATE  INDEX AC_NUM_FK ON WAREHOUSE
(AC_NUM   ASC);



CREATE  INDEX P_NUM_FK ON WAREHOUSE
(P_NUM   ASC);



ALTER TABLE CD_ORDER
	ADD (CONSTRAINT R_12 FOREIGN KEY (C_NUM) REFERENCES CUSTOMER (C_NUM) ON DELETE SET NULL);



ALTER TABLE ORDER_CHART
	ADD (CONSTRAINT R_16 FOREIGN KEY (CD_NUM) REFERENCES CD_ORDER (CD_NUM) ON DELETE SET NULL);



ALTER TABLE ORDER_CHART
	ADD (CONSTRAINT R_18 FOREIGN KEY (P_NUM) REFERENCES PRODUCT (P_NUM) ON DELETE SET NULL);



ALTER TABLE WAREHOUSE
	ADD (CONSTRAINT R_19 FOREIGN KEY (AC_NUM) REFERENCES ACCOUNT (AC_NUM) ON DELETE SET NULL);



ALTER TABLE WAREHOUSE
	ADD (CONSTRAINT R_20 FOREIGN KEY (P_NUM) REFERENCES PRODUCT (P_NUM) ON DELETE SET NULL);


